spring:
  application:
    name: msemail
  datasource:
    url: jdbc:postgresql://localhost:5432/email?createDatabaseIfNotExist=true
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
  mail:
    host: smtp.gmail.com
    port: 587
    username: moisesestevaosilva2004@gmail.com
    password: bgijkzplmjutfhof
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}




