
spring:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  application:
    name: msinventory
  datasource:
    url: jdbc:mysql://localhost:3306/inventory?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}



